version: "3.9"
services:
  db-accounts:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
    env_file:
      - /src/.env
    ports:
      - "5433:5432"
    networks:
      - mc_network
  web-accounts:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8100
    volumes:
      - ./src:/app/src
    ports:
      - "8100:8100"
    networks:
      - mc_network
    depends_on:
      - db-accounts
networks:
  mc_network:
    external: true