version: "3.9"
services:
  db-profiles:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - /src/.env
    ports:
      - "5433:5432"
    networks:
      - mc_network
  web-profiles:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8100
    volumes:
      - ./src:/app/src
    ports:
      - "8100:8100"
    networks:
      - mc_network
    depends_on:
      - db-profiles
networks:
  mc_network:
    external: true