version: "3.13"
services:
  db-accounts:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
    env_file:
      - /src/.env
    ports:
      - "5433:5432"
    networks:
      - mc_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  web-accounts:
    build: .
    command: /app/start.sh
    volumes:
      - ./src:/app/src
    ports:
      - "8100:8100"
    networks:
      - mc_network
    depends_on:
      db-accounts:
        condition: service_healthy
networks:
  mc_network:
    external: true