# Generated by Django 5.1 on 2024-09-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
    ]
